CREATE TABLE IF NOT EXISTS onboarding_state (
  id TINYINT UNSIGNED NOT NULL DEFAULT 1,
  status ENUM('NAO_INICIADO', 'EM_ANDAMENTO', 'PARCIAL', 'BLOQUEADO', 'PRONTO_LOGICO', 'CONCLUIDO') NOT NULL DEFAULT 'NAO_INICIADO',
  current_step ENUM('ESCOLA_CONTA_ADMINISTRADOR', 'AREA', 'CATRACA', 'CURSO', 'TURMA', 'EMPRESA', 'SALA', 'PESSOAS') NULL,
  completed_steps JSON NOT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  CONSTRAINT chk_onboarding_state_singleton CHECK (id = 1),
  CONSTRAINT chk_onboarding_state_steps CHECK (JSON_TYPE(completed_steps) = 'ARRAY')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
